[package]
name = "growingcultures-api"
version = "0.1.0"
edition = "2021"
description = "Read-only access to Points-of-Interest (POIs) and tours"

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
utoipa.workspace = true
